spring.application.name=report-service

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

aws.region=${AWS_REGION:eu-central-1}
aws.s3.bucket-name=${S3_BUCKET_NAME:cloud-security-ai-assistant-bucket}