spring.application.name=gateway-service

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webmvc.routes[0].id=finding-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://FINDING-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/findings/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=ai-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/ai/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=report-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://REPORT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/reports/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8084/realms/cloud-security/protocol/openid-connect/certs}