spring.application.name=finding-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:h2:mem:findingsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

aws.region=${AWS_REGION:eu-central-1}
aws.dynamodb.findings-table-name=${DYNAMODB_FINDINGS_TABLE_NAME:cloud-security-findings}